camaraproject/DeviceStatus

code/API_definitions/check-device-connectivity.yaml

* Add new return parameters Country Code and Country Name 
More Details for Roaming Status #18 :- With reference to this issue on CAMARA we  added new return parameter 
1. Country Code
2. Country Name

Add new return parameters Country Code and Country Name

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_bug_template.md
.github/ISSUE_TEMPLATE/issue_correction_template.md
.github/ISSUE_TEMPLATE/issue_documentation_template.md
.github/ISSUE_TEMPLATE/issue_enhancement_template.md
.github/ISSUE_TEMPLATE/issue_pm_template.md
.github/ISSUE_TEMPLATE/issue_tests_template.md
.github/pull_request_template.md

Adds agreed PR and Issue templates to the Device Status github repository
No associated issue in Device Status
Templates introduced by [this ](https://github.com/camaraproject/WorkingGroups/pull/174) PR
None
```
release-note
- Add PR and Issue Templates
```
None

Add PR and Issue Templates

---

code/API_definitions/device-status.yaml

* cleanup
- manage inheritance in Event models and derived classes
- rename classes to respect naming rules (class name in CamelCase)
- reorder object declaration to help generators (see allOf directives for inheritance)
Fixes #
```
release-note
```
```
docs
```

Cleanup model

---

code/API_definitions/device-status.yaml

* correction
Replace subscriptionId by eventSubscriptionId everywhere
Integration of remarks from @fernandopradocabrillo.
```
replace subscriptionId by eventSubscriptionId
```

fix(openapi): replace subscriptionId by eventSubscriptionId

---

code/API_definitions/device-status.yaml

New proposal following our discussion on issue  #17 . 
Not for merging at this stage but to get team feedback - I will like to use the work we're doing here to contribute to API guidelines for subscription/notification model.

Adding notification/subscription for Device Status

---

code/API_definitions/device-status.yaml

This PR creates a new endpoint "/connectivity" to check the current network status of a device.
Fixes #34

add /connectivity - endpoint to check the network status of a device

---

CODEOWNERS
MAINTAINERS.MD

Adding Akos Hunyadi @akoshunyadi to MAINTAINER.md and CODEOWNER file.
Fixes #85 
See issue #85 
na

Add additional maintainer and codeowner (see #85)

---

code/API_definitions/device-status.yaml

Make subscriptionDetail/device and CloudEvent/data mandatory
Fixes #84

Make subscriptionDetail/device and CloudEvent/data mandatory

---

code/API_definitions/device-status.yaml

Align Device definition - in particular ipV6 definition with other CAMARA APIs
* correction
Align Device definition - in particular ipV6 definition with other CAMARA APIs
Fix device definition (copied from Device location)
Fixes #91 
```
release-note
- Aligned Device definition and in particular IPv6 with CAMARA common definition
```
```
docs
```

Update device-status.yaml to align Device definition

---

code/API_definitions/device-status.yaml

* correction
Proposed changes correct errors detected by:
- Spectral (OAS linting tool):
- error  parser                          Mapping key must be a string scalar rather than number
- oas3-valid-schema-example       "example" property type must be string
-  error  oas3-valid-media-example        "id" property type must be string
- yamllint:
- [trailing-spaces] trailing spaces
- [colons] too many spaces before colon
- [brackets] too many spaces inside brackets
The version was changed to: `0.5.0-wip`
Fixes #94 and #97 
The output of linting can be seen after expanding "Megalinter" section of workflow results: 
https://github.com/rartych/DeviceStatus/actions/runs/7209051170/job/19639229860
```
Corrections resolving linting errors introduced
```
This section …

Corrections resolving linting errors

---

code/API_definitions/device-status.yaml

* correction
Moves the "countryCode" parameter out of the "device"-parameter.
Adds "countryName" inside of the corresponding example.

fix: move "countryCode" out of "device" in ROAMING_CHANGE_COUNTRY-example

---

code/API_definitions/device-status.yaml

* correction
Correct the description for "subscription-ends" that this event will be send, when subscription expire time is optionally set by the requester.
Fixes #116

fix: change description that subscriptionExpireTime is optional

---

code/API_definitions/device-status.yaml

* correction
In the examples of callback CloudEvents for roaming-status, there is the subscriptionId given, but not in the corresponding component.
This will be fixed with this PR.

fix: add missing "subscriptionId" in "RoamingStatus"-data for CloudEvent

---

code/API_definitions/device-status.yaml

Small update of in-line documentation for Roaming to clarify that country information can optionally be returned in the response. Previous documentation implied that country information was mandatory when roaming is true.
Fixes #124 
As discussed in DeviceStatus meeting on 13-03-24. It was agreed that country information is optional in cases of roaming=true.
```
release-note
Updated in-line documentation for Roaming to clarify that country information in response is optional.
```

Updated in-line documentation for Roaming to clarify that country information can optionally be returned in the response.

---

code/API_definitions/device-status.yaml

* bug
Change old INVALID_INPUT 400 errors for INVALID_ARGUMENTS as stated in the commonalities guidelines

fix: change INVALID_INPUT for INVALID_ARGUMENT according to guidelines

---

code/API_definitions/device-status.yaml

* correction
This PR makes more clear, what Event-Types are used for notification and updates some descriptions of the components.
Also the "subscriptionId" in the "subscription-ends"-event is now mandatory.
Fixes #142

renaming "EventType"-components to be more clear & update component descriptions

---

code/API_definitions/device-status.yaml

* correction
As required in Commonalities, this PR makes the '+' sign mandatory for the phoneNumber.
Fixes #136 
```
release-note
``` Make '+' mandatory for phoneNumber + update documentation & examples accordingly.
```
docs
```

Make '+' mandatory for phoneNumber

---

CHANGELOG.md
README.md
code/API_definitions/device-status.yaml

Prepare the release version 0.6 with the Device Status API version 0.6.0-alpha.1
Requesting for detailed review, since this is the first release following the new releasing guidelines.

Prepare release r0.6

---

code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status.yaml

Shift device structure cardinality to optional has the device identifier could be obtained from the 3-legs process.
Fixes #173 
```
release-note
- Device structure is now optional has the device identifier could be obtained from the 3-legs process.
```
```
docs
```

Switch device structure to optional

---

code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status.yaml

Alignement of errors according to Commonalities guideline.
Fixes #180 #181 
```
release-note
- Aligned error code list with Commonalities for device-reachability-status and device-roaming-status API
```

`device-reachability-status` & `device-roaming-status`: Alignment of errors with Commonalities

---

README.md

* correction
Removes the scope limit of DeivceStatus for 4G and 5G
Fixes #163

Removing note that the API-scope is limited to 4G and 5G

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml

Alignement of errors according to Commonalities guideline.
Fixes #184  
```
release-note
- Aligned error scenarios list with Commonalities for subscription APIs
```

Subscription-APIs: Alignment of errors with Commonalities

---

CHANGELOG.md
README.md
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/API_definitions/device-roaming-status.yaml
documentation/API_documentation/device-reachability-status-API-Readiness-Checklist.md
documentation/API_documentation/device-reachability-status-subscriptions-API-Readiness-Checklist.md
documentation/API_documentation/device-roaming-status-API-Readiness-Checklist.md
documentation/API_documentation/device-roaming-status-subscriptions-API-Readiness-Checklist.md

Prepare release r1.1

---

code/API_definitions/device-roaming-status-subscriptions.yaml

* correction
Missing enums added to TerminationReason
Fixes #203 
```
Missing enums added to TerminationReason
```

device-roaming-status-subscriptions: add missing enums to TerminationReason

---

code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status.yaml

In these 2 APIs the device attribute is optional in the request, which allows using the device from the access token. 
CAMARA Commonalities recommends for this case a template to be included in the info.description field.
Now this template has been inserted.
Fixes #205 
```
Added device identifier template to info.description
```

Add device id template to the retrieve APIs

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/API_definitions/device-roaming-status.yaml

* bug
This PR adds the missing components, which were referenced in the `protocol`-discriminator
Fixes #207

Add missing `protocol`-components for device-roaming-status-subscriptions

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml

Extended the description for the reachability types to make them unambiguous.
Fixes #213 
```
The description of the reachability types has been adjusted to make them unambiguous.
```

Update description of the reachability types

---

CHANGELOG.md
README.md
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/API_definitions/device-roaming-status.yaml
documentation/API_documentation/device-reachability-status-API-Readiness-Checklist.md
documentation/API_documentation/device-reachability-status-subscriptions-API-Readiness-Checklist.md
documentation/API_documentation/device-roaming-status-API-Readiness-Checklist.md
documentation/API_documentation/device-roaming-status-subscriptions-API-Readiness-Checklist.md

Prepare patch release r1.3
- update the modified OAS files (compared to r1.2)
- update change log

Prepare release r1.3

---

code/API_definitions/device-reachability-status.yaml
code/Test_definitions/device-reachability-status.feature

Adds a support, when a device is reachable via multiple connectivity-types, e.g. SMS & DATA.
Fixes #140

[device-reachability-status]: support for reachability with multiple connectivity-types

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml

* correction
Removing this `allOf`.
It was discovered for some code-generator, it will produce unexpected behaviours having the `description` inside the `allOf`.
Fixes #225
```
[device-status-subscriptions]: remove `allOf` in `sinkCredential` in `SubscriptionRequest` component
```

[device-status-subscriptions]: remove `allOf` in `sinkcredential`

---

code/API_definitions/connected-network-type-subscriptions.yaml

* correction
Remove allOf from sinkCredential. allOf with description causes problems in some code-generator
Fixes #243 
```
remove allOf with description in sinkCredential
```

[connected-network-type-subscriptions] remove allOf in sinkCredential

---

code/API_definitions/connected-network-type-subscriptions.yaml

Clarification for initialEvent for connected-network-type-subscriptionsns.yaml
Fixes #222 
```
release-note
- documentation: Clarification for initialEvent for connected-network-type-subscriptions
```
```
docs
```

Clarification for initialEvent for connected-network-type-subscriptions

---

code/Test_definitions/connected-network-type-subscriptions.feature
code/Test_definitions/connected-network-type.feature
code/Test_definitions/device-reachability-status-subscriptions.feature
code/Test_definitions/device-reachability-status.feature
code/Test_definitions/device-roaming-status-subscriptions.feature
code/Test_definitions/device-roaming-status.feature

In order to participate in the next meta release, we need basic test cases for the new APIs.
Fixed typos and format issues in the existing ones.
Fixes #234

Add basic testcases for the new APIs conncted-network-type and connected-network-type-subscriptions

---

code/API_definitions/connected-network-type-subscriptions.yaml
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/Test_definitions/device-reachability-status-subscriptions.feature
code/Test_definitions/device-reachability-status.feature

* correction
This PR removes the `INVALID_TOKEN_CONTEXT` error-code to allign on Commonalities v0.5.0-rc.1
Fixes #256 
```
release-note
* Remove INVALID_TOKEN_CONTEXT error-code based on Commonalities 0.5.0-rc.1
```

Remove INVALID_TOKEN_CONTEXT error-code based on Commonalities 0.5.0-rc.1

---

code/Test_definitions/connected-network-type-subscriptions.feature
code/Test_definitions/connected-network-type.feature
code/Test_definitions/device-reachability-status-subscriptions.feature
code/Test_definitions/device-reachability-status.feature
code/Test_definitions/device-roaming-status-subscriptions.feature
code/Test_definitions/device-roaming-status.feature

* tests
This PR extends the testcases for:
* device-reachability-status
* device-roaming-status
* aligns all *.feature - files on a common style.
* removes error-code `MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED` from `code/API_definitions/connected-network-type-subscriptions.yaml`
Fixes #236 
```
release-note
[device-reachability-status, device-roaming-status]: Add extended test cases for the planned stable apis
```

Add extended test cases for device-roaming-status and device-reachability-status + refactor *.feature-files
