camaraproject/DeviceStatus

code/API_definitions/check-device-connectivity.yaml

Initial contribution of the API spec check-device-connectivity with the version 0.2.0. #2 
The API enables to query the roaming status of a UE. further extensions with other connectivity related functionalities are possible.

Initial contribution of API spec check-device-connectivity v0.2.0

---

documentation/SupportingDocuments/Roaming API Proposal - Vodafone.md

Upload of original Roaming API proposal from Vodafone

Upload Roaming API Proposal - Vodafone.md

---

README.md

Meeting Dates updated 

---

code/API_definitions/device-status.yaml

1. Fix typo in Response of country Name
2. Update the file name to> device-status.yaml

Fix Typo in response of CountryName & File name

---

CHANGELOG.md

This is the change log for release v0.2.0

Adding CHANGELOG

---

code/API_definitions/device-status.yaml

This PR is opened to handle [issue#14](https://github.com/camaraproject/DeviceStatus/issues/14). 
Besides fixing error codes & error model, additionally I add a new error 504/Timeout that I think it could be useful. 
Looking forward to getting your feedback.

Errors definition alignment with guidelines

---

CHANGELOG.md

Added release notes for v0.4.1 to change log

Update CHANGELOG for v0.4.1

---

CHANGELOG.md
documentation/API_documentation/Connectivity_API.md

Current documentation is out of date
Fixes #37
Documentation is for v0.4.1. Someone still needs to update it for v0.5.0 before that is released.
```
release-note
- Update of documentation for v0.4.1
```
This section is intentionally left blank.

Merge of documentation for v0.4.1 into main

---

documentation/SupportingDocuments/decision-support-1-or-2-apis.md

API decision document: DT's preference added

Update API decision document with DT's preference

---

documentation/SupportingDocuments/decision-support-1-or-2-apis.md

Contributing additional arguments to the documented pro/cons + Telefónica's preference

feat: telefonica decision single vs multiple apis

---

MAINTAINERS.MD

Role change
Fixes #
```
release-note
```
```
docs
```

maintainers list updated

---

documentation/MeetingMinutes/MoM-2023-07-19.md

MoM 2023-07-19

---

documentation/MeetingMinutes/MoM-2023-10-11.md

MoM-2023-10-11

---

documentation/MeetingMinutes/MoM-2023-09-27.md

MoM-2023-09-27

---

code/API_definitions/device-status.yaml

Aligned with CloudEvents format as defined in Commonalities here: https://github.com/camaraproject/Commonalities/pull/56 
Fixes #74 #57 
```
- Provide roaming status subscription & notification aligned with Cloudevents structure.
```
```
docs
```

Added Notification management aligned with CloudEvents format

---

documentation/MeetingMinutes/MoM-2023-10-25.md

MoM-2023-10-25

---

documentation/MeetingMinutes/MoM-2023-11-08.md

MoM-2023-11-08

---

documentation/MeetingMinutes/MoM-2023-11-22.md

MoM-2023-11-22

---

documentation/MeetingMinutes/MoM-2023-12-06.md

MoM-2023-12-06

---

CHANGELOG.md
README.md
code/API_definitions/device-status.yaml

Create release candidate 0.5.0-rc
Fixes #82 
Should be merged after the PR merged for #84

Create release candidate 0.5.0-rc

---

documentation/MeetingMinutes/MoM-2024-01-17.md

MoM-2024-01-17

---

documentation/MeetingMinutes/MoM-2024-02-14.md

MoM-2024-02-14

---

documentation/MeetingMinutes/MoM-2024-02-28.md

MoM 2024-02-28

---

code/API_definitions/device-status.yaml

Reverts camaraproject/DeviceStatus#111

Revert "Update device-status.yaml"

---

documentation/MeetingMinutes/MoM-2023-03-13.md
documentation/MeetingMinutes/MoM-2024-03-13.md

MoM-2024-03-13

---

documentation/MeetingMinutes/MoM-2024-03-27.md

MoM-2024-03-27

---

.github/workflows/megalinter.yml
.github/workflows/spectral_oas_lint.yml
.spectral.yml
.yamllint.yaml
lint_function/camara-language-avoid-telco.js
lint_function/camara-reserved-words.js
lint_function/camara-security-no-secrets-in-path-or-query-parameters.js

The changes follow the instructions in https://github.com/camaraproject/Commonalities/blob/main/documentation/API-linting-Implementation-Guideline.md
Fixes #
```
Linting ruleset configured in Github Actions
```
[CAMARA API Linting Rules Documentation](https://github.com/camaraproject/Commonalities/blob/main/documentation/Linting-rules.md)

Adding configuration for Github Actions with linting ruleset

---

CODEOWNERS
MAINTAINERS.MD

159 update and review codeowners and maintainersmd file

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/API_definitions/device-roaming-status.yaml

* correction
Removes `terms of service` and `contact` as they are optional and not needed.
Fixes #182

Remove `terms of service` and `contact`

---

code/API_definitions/device-roaming-status.yaml

* correction
Renamed `RequestRoamingStatus` to `RoamingStatusRequest`
Fixes #192

Renamed RequestRoamingStatus to RoamingStatusRequest

---

README.md

Scope section of README needs to be updated and improved following API evolution
N/A
None
```
release-note
- Update Scope section of README.md
```
None

Update Scope section of README.md

---

code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status.yaml

* correction
Remove 405 code in device-reachability-status.yaml & device-roaming-status.yaml
Fixes #197 
Version reset to wip
```
release-note
- Remove 405 code in device-reachability-status.yaml & device-roaming-status.yaml
```
```
docs
```

Remove 405 code in the yaml

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml

* correction
Correct the examples
Fixes #209

Correct the examples for sub - initialEvent and error MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED

---

code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/API_definitions/device-roaming-status.yaml

* cleanup
Reset version numbers to wip for future development
Fixes #
None
```
release-note
- Reset version numbers to wip
```
None

Reset version numbers to wip

---

code/API_definitions/connected-network-type-subscriptions.yaml
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml

* correction
220 & 238
Fixes #
```
release-note
```
```
docs
```

Update Subscription Yaml file for issue 220 and 238

---

code/API_definitions/connected-network-type-subscriptions.yaml
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml

* correction
* cleanup
Fixes #235
Fixes #241 
```
release-note
```
```
docs
```

Alignment with Commonalities Subscription Model - APIs Subscription

---

code/API_definitions/connected-network-type-subscriptions.yaml
code/API_definitions/connected-network-type.yaml
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-reachability-status.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml
code/API_definitions/device-roaming-status.yaml
code/Test_definitions/connected-network-type-subscriptions.feature
code/Test_definitions/connected-network-type.feature
code/Test_definitions/device-reachability-status-subscriptions.feature
code/Test_definitions/device-reachability-status.feature
code/Test_definitions/device-roaming-status-subscriptions.feature
code/Test_definitions/device-roaming-status.feature

Reset version numbers to wip following publication of release candidate
Fixes #N/A
Merge this PR next
```
release-note
- Reset version numbers to wip following r2.1
```
None

Reset version numbers to wip following r2.1

---

code/API_definitions/connected-network-type-subscriptions.yaml
code/API_definitions/device-reachability-status-subscriptions.yaml
code/API_definitions/device-roaming-status-subscriptions.yaml

* correction
For compliance with [Commonalities 0.5.0](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#resource-based-explicit-subscription)
Fixes # N/A
None
```
release-note
- Change event notification sink format from url to uri
```
None

Change event notification sink format from url to uri
